manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  self:
    path: iomico_blinky
  #
  # Please add items below based on alphabetical order
  projects:
    - name: zephyr
      remote: upstream
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nordic # required by the custom_plank board (Nordic based)

        #if not using name-allowlist, the following is an example of how to
        #specify the modules to be imported one by one
          #  projects:
          #        - name: cmsis
          #        #if not specified, the default remote is used
          #          remote: upstream
          #          revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
          #          path: modules/hal/cmsis
          #          groups:
          #            - hal
