# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim

  group-filter: [-babblesim, -optional]

  #
  # Please add items below based on alphabetical order
 projects:
    - name: zephyr
      remote: upstream
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nordic # required by the custom_plank board (Nordic based)
          #  projects:
          #        - name: cmsis
          #        #if not specified, the default remote is used
          #          remote: upstream
          #          revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
          #          path: modules/hal/cmsis
          #          groups:
          #            - hal
          #        - name: cmsis-dsp
          #          remote: upstream
          #          revision: 6489e771e9c405f1763b52d64a3f17a1ec488ace
          #          path: modules/lib/cmsis-dsp
          #        - name: hal_nordic
          #          revision: cb7600a1be4c8b177867e6d463729c07dd3f6d73
          #          path: modules/hal/nordic
          #          groups:
          #            - hal
          #        - name: hal_ti
          #          remote: upstream
          #          revision: 2e7b95ad079e9f636884eedc6853e6ad98b85f65
          #          path: modules/hal/ti
          #          groups:
          #            - hal

  self:
    path: iomico_blinky
    west-commands: scripts/west-commands.yml
    # import: submanifests
